In [ ]:
import numpy as np
#creating arrays
arr = np.array([1,2,3,4,5],dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [ ]:
import numpy as np
a1=np.eye(4)#identity matrix
print(a1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
a=np.full((2,2),3)
print(a)
print(a.itemsize)

[[3 3]
 [3 3]]
8


In [ ]:
import numpy as np
x=[1,2,3]
a=np.asarray(x)#symmetric matrix
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))#[1*2+4*2+1*0=10.0]
print(np.outer(x,y))#1*2,1*2,1*1/4*2,,4*2,4*1...
print(np.cross(x,y))


10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [ ]:
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7])
print(np.rint(a))

[1. 2. 3. 4. 6. 7. 8.]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
print(np.true_divide(a,b))

[1. 1. 1. 1. 1.]


In [ ]:
a=np.array([1,1,2,2,3,3])
print(np.unique(a))

[1 2 3]


In [ ]:
a=np.array([[1,2],[2,3]])
b=np.array([[3,4],[4,5]])
print(np.union1d(a,b))
print(np.setdiff1d(a,b))

[1 3 4 5]
[1]


In [ ]:
a=8
b=6
c=np.hypot(a,b)
print(c)

10.0


In [ ]:
x=np.sin(0)
y=np.cos(0)
print(x,y)

0.0 1.0


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.divmod(a,b))


(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.mod(a,b))


[10  0  0  0  0 10]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.multiply(a,b))
print(np.matmul(a,b))

[ 200  441   60  800 1250 1500]
4251


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)

[[ 1.76729736  1.54635394  1.87765279]
 [-1.42817592 -0.91337007 -0.95090311]]


In [ ]:
from numpy import random
x=random.normal(loc=1,scale=2,size=(2,3))#loc=mean,sacle=s.d
print(x)

[[-2.7136086   2.75410056  2.5664063 ]
 [-1.11387487  2.37607169  3.04461516]]


In [ ]:
x=random.binomial(n=12,p=0.5,size=(10))#n=no of trails,p=probability
print(x)

[5 7 6 4 4 5 6 7 9 7]


In [ ]:
x=random.poisson(lam=2,size=10)#lambda=lam
print(x)
c=random.choice([2,3,1])
print(c)

[1 1 0 4 1 3 0 5 6 0]
3


In [ ]:
x=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(x)

[[5 3 5 5 3]
 [5 5 5 5 5]
 [5 3 3 5 3]]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.divide(a,b))

[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
a=np.array([[1,2],[2,3]])
b=np.array([[3,4],[4,5]])
print(np.intersect1d(a,b))

[3]


In [ ]:
a = np.arange(10,dtype=float)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
b= np.arange(0,1000,5)
print(b)
b1=np.savetxt("/content/arange1.txt",b)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [ ]:
a = np.random.rand()
print(a)
b=np.random.randint(0,2)
print(b)

0.5922319513640679
1


In [ ]:
m=np.array([[1,2],[3,4]])
print(type(m))
print(m.shape)
print(m.ndim)

<class 'numpy.ndarray'>
(2, 2)
2


In [ ]:
a=np.linspace(0.5,2,5)
print(a)

[0.5   0.875 1.25  1.625 2.   ]


In [ ]:
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
c=np.dot(a,b)
print(a*b) #element mul
print(a@b) #matrix mul
print(c) #matrix mul

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
a1=np.floor(np.random.random((2,12)))
a2=np.floor(np.random.random((2,2)))
print(a.sum())
print(a)
print(a.sum(axis=1))#row wise add
print(a.sum(axis=0))#col wise add
print(a1)
print(a2)
a3=np.ceil(np.random.random((2,12)))
print(a3)

6
[[1 1 1]
 [1 1 1]]
[3 3]
[2 2 2]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
a=np.array([[1,2],[2,3]])
print(a.max(axis=1))
print(a.max(axis=0))
print(a.min(axis=0))
print(a.min(axis=0))

[2 3]
[2 3]
[1 2]
[1 2]


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.cumsum(axis=0))
print(a.cumsum(axis=1))

[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


In [ ]:
a=np.array([1,2,3,4,5,6])
print(a.resize(3,2))#previously its one dim,now we changing dim.thats why we get none in o/p.
print(a)
print(a.shape)

None
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
a=np.array([1,2,3,4,5,6])
print(a.resize(2,3))
b=np.array([6,5,4,3,2,1])
print(b.resize(2,3))
print(np.vstack((a,b)))#vstack-vertical stack,concatinated 2 matrices
print(np.hstack((a,b)))#hstack-horizontal stack,joining 2 matrices

None
None
[[1 2 3]
 [4 5 6]
 [6 5 4]
 [3 2 1]]
[[1 2 3 6 5 4]
 [4 5 6 3 2 1]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print(np.dstack(a))
#no.of rows become no.of groups
#col become rows and group become col

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#Array manipulation
arr = np.array([1,2,3,4,5])
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)
sa=arr[2:4]
print(sa) #sliced func
a=np.array([1,2,3,4,5,6,7,8])
b=a.T #T-transpose
print(b)
b=np.split(a,4)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]
[3 4]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)

[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
data = np.loadtxt("/content/drive/MyDrive/dataset/data.txt",dtype=int)
d=np.savetxt("/content/dap1.txt",data)
print(d)
print(data)

None
[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]]


In [ ]:
z = np.zeros((3,3),dtype=float)
print(z)
ones_arr=np.ones((2,2),dtype=int)
print(ones_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]]
